/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RenderSiteRouteImport } from './routes/render-site'
import { Route as ApiPublicRenderSiteRouteImport } from './routes/api/public/render-site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderSiteRoute = RenderSiteRouteImport.update({
  id: '/render-site',
  path: '/render-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderSiteRoute = ApiPublicRenderSiteRouteImport.update({
  id: '/api/public/render-site',
  path: '/api/public/render-site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/render-site': typeof RenderSiteRoute
  '/api/public/render-site': typeof ApiPublicRenderSiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/render-site': typeof RenderSiteRoute
  '/api/public/render-site': typeof ApiPublicRenderSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/render-site': typeof RenderSiteRoute
  '/api/public/render-site': typeof ApiPublicRenderSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/render-site' | '/api/public/render-site'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/render-site' | '/api/public/render-site'
  id: '__root__' | '/' | '/render-site' | '/api/public/render-site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RenderSiteRoute: typeof RenderSiteRoute
  ApiPublicRenderSiteRoute: typeof ApiPublicRenderSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render-site': {
      id: '/render-site'
      path: '/render-site'
      fullPath: '/render-site'
      preLoaderRoute: typeof RenderSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-site': {
      id: '/api/public/render-site'
      path: '/api/public/render-site'
      fullPath: '/api/public/render-site'
      preLoaderRoute: typeof ApiPublicRenderSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RenderSiteRoute: RenderSiteRoute,
  ApiPublicRenderSiteRoute: ApiPublicRenderSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
